ServerAddress: ":8080"
MaxConnections: 10000
LogLevel: "info"
MaxRequestsPerConn: 5000 # Maximum requests per connection before a new connection is established
ClientReadTimeoutSeconds: 15
ClientWriteTimeoutSeconds: 15
ClientMaxIdleConnDurationSeconds: 60
