name: CI Build and Test

on:
  push:
    branches:
      - master # Or main, if you've switched
  pull_request:
    branches:
      - master # Or main

jobs:
  build_test_lint_tag:
    name: Build, Test, Lint, and Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessary to push tags if the push is to the master/main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2" # From go.mod and README

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./... --timeout 5m

      - name: Run tests
        run: go test -v ./...

      - name: Build Go Package
        run: go build -v -o gok-proxy-proxy ./cmd/proxy/
        # -v for verbose output
        # Output artifact is gok-proxy-proxy

      - name: Create and Push Tag (only on push to master/main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Or refs/heads/main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Generate a tag name. Example: build-20231027-143000
          # For actual releases, consider a semantic versioning strategy.
          TAG_NAME="build-$(date +'%Y%m%d-%H%M%S')"
          echo "Generated tag name: $TAG_NAME"

          git tag "$TAG_NAME"
          echo "Created tag $TAG_NAME locally."

          git push origin "$TAG_NAME"
          echo "Pushed tag $TAG_NAME to remote."
